# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: ['beta']
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

#      - name: Semantic Version
#        run: npx dwmkerr/standard-version --prerelease beta --packageFiles pom.xml --bumpFiles pom.xml
#        env:
#          GITHUB_TOKEN: ${{ github.token }}

##        https://github.com/marketplace/actions/automated-github-action-maven-version-bump
#      - name: Automated Github Action Maven Version Bump
#        uses: mickem/gh-action-bump-maven-version@v1.0.0

      - name: Commit files
        run: |
          mvn versions:set -DnewVersion=1.1.3-SNAPSHOT
          git config remote.origin.url https://github.com/cmani97/demolibrary.git
          git config --global user.name "cmani97"
          git config --global user.email "cmani09797@gmail.com"
          git add -A
          git commit -am "version beta update"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages  Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}