# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: ['master', 'beta']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      VERSION: ${project.version}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
#          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: git config
        run: |
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"

      - name: Semantic Version
        run: npx dwmkerr/standard-version --first-release --packageFiles pom.xml --bumpFiles pom.xml

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages  Apache Maven
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit files
        run: |
          git add -A
          git commit -am "version update"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

#      - name: Determine version and create changelog
#        id: bumper
#        uses: tomerfi/version-bumper-action@1.1.2
#        with:
#          changelog: true
#          label: -beta


#      - name: Standard Version
#        env:
#          GITHUB_TOKEN: ${{ github.token }}
#        run: npx dwmkerr/standard-version --packageFiles pom.xml --bumpFiles pom.xml

##        https://github.com/marketplace/actions/automated-github-action-maven-version-bump
#      - name: Automated Github Action Maven Version Bump
#        uses: mickem/gh-action-bump-maven-version@v1.0.0

#      - name: Semantic Version
#        run: npx dwmkerr/standard-version --prerelease beta --packageFiles pom.xml --bumpFiles pom.xml
#        env:
#          GITHUB_TOKEN: ${{ github.token }}

#      - name: Semantic Version
#        run: mvn semver:finalize-current


#      - name: Version increment for master
#        if: github.ref == 'refs/heads/master'
#        run: |
#          mvn semver:increment-major
#          mvn semver:finalize-current
#
#      - name: Version increment for beta
#        if: github.ref == 'refs/heads/beta'
#        run: |
#          mvn semver:increment-minor
#          mvn semver:update-pre-release -Dset=beta